---
- platform: template
  switches:
    living_room_media_system:
      unique_id: 53a58130-6940-4c3b-a667-506284826911
      friendly_name: Living Room Media System
      icon_template: mdi:power
      value_template: "{{ is_state('media_player.denon_avr_x1500h', 'on') }}"
      turn_on:
        service: script.living_room_media_system_power_on
      turn_off:
        service: script.living_room_media_system_power_off
