---
blueprint:
  name: Plug Temperature Alarm
  domain: automation
  input:
    sensor_target:
      name: Sensors to watch
      selector:
        target:
          entity:
            domain: sensor
            device_class: temperature
    temperature_threshold:
      name: Temperature threshold (°C)
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: °C
    ntfy_topic:
      name: Topic to send notifications to
      default: tuxnet-home-security
      selector:
        text:
    alert_title:
      name: Alert title
      default: PLUG TEMPERATURE ALARM
      selector:
        text:
    alert_tags:
      name: Alert tags
      default:
        - electric_plug
        - rotating_light
      selector:
        object:
    alert_priority:
      name: Alert priority
      default: max
      selector:
        select:
          options:
            - min
            - low
            - default
            - high
            - max
    cleared_title:
      name: Cleared title
      default: PLUG TEMPERATURE ALARM CLEARED
      selector:
        text:
    cleared_tags:
      name: Cleared tags
      default:
        - electric_plug
        - green_circle
      selector:
        object:
    cleared_priority:
      name: Cleared priority
      default: high
      selector:
        select:
          options:
            - min
            - low
            - default
            - high
            - max

variables:
  temperature_threshold: !input temperature_threshold

trigger:
  - trigger: temperature.crossed_threshold
    target: !input sensor_target
    options:
      threshold:
        type: above
        value:
          number: !input temperature_threshold
          unit_of_measurement: °C
      behavior: each
    id: alert
  - trigger: temperature.crossed_threshold
    target: !input sensor_target
    options:
      threshold:
        type: below
        value:
          number: !input temperature_threshold
          unit_of_measurement: °C
      behavior: each
    id: cleared
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: alert
        sequence:
          - action: rest_command.ntfy_notify
            data:
              topic: !input ntfy_topic
              title: !input alert_title
              tags: !input alert_tags
              priority: !input alert_priority
              markdown: false
              message: |-
                Name: {{ trigger.to_state.attributes.friendly_name }}
                Started: {{ as_local(trigger.to_state.last_changed).strftime('%Y-%m-%d %H:%M:%S') }}
                Temperature: {{ trigger.to_state.state }}°C
                Threshold: {{ temperature_threshold }}°C
                Entity ID: {{ trigger.entity_id }}
      - conditions:
          - condition: trigger
            id: cleared
        sequence:
          - action: rest_command.ntfy_notify
            data:
              topic: !input ntfy_topic
              title: !input cleared_title
              tags: !input cleared_tags
              priority: !input cleared_priority
              markdown: false
              message: |-
                Name: {{ trigger.to_state.attributes.friendly_name }}
                Started: {{ as_local(trigger.from_state.last_changed).strftime('%Y-%m-%d %H:%M:%S') }}
                Ended: {{ as_local(trigger.to_state.last_changed).strftime('%Y-%m-%d %H:%M:%S') }}
                Temperature: {{ trigger.to_state.state }}°C
                Threshold: {{ temperature_threshold }}°C
                Entity ID: {{ trigger.entity_id }}
mode: parallel
