---
extends: default

ignore: |
  lib/
  .sops.yaml
  .pre-commit-config.yaml
  sites/**/configuration/secrets.yaml
  sites/**/configuration/secrets.enc.yaml

rules:
  comments-indentation: false
  line-length: false
  empty-lines:
    max: 2
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 1
  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 1
  truthy:
    ignore:
      - .github/
