---
- alias: garden switch 1 to outlet
  trigger:
    platform: state
    entity_id: switch.fds3_2
  action:
    service_template: "switch.turn_{{ trigger.to_state.state }}"
    entity_id: switch.fds4_2
