---
- alias: turn off living room projector when avr turns off
  trigger:
    platform: state
    entity_id: media_player.denon_avr_x1500h
    to: "off"
  action:
    - delay: 2
    - service: remote.turn_off
      entity_id: remote.living_room_projector
