---
api_version: 2
ssl: false
host: telegraf.home-assistant-telegraf
port: 8086
organization: home-data
bucket: homeassistant
token: !secret influxdb_token
default_measurement: state
tags:
  source: homeassistant
tags_attributes:
  - friendly_name
ignore_attributes: !include ignore_attributes.yaml
include: !include includes.yaml
exclude: !include excludes.yaml
