---
- alias: "Living Room: Media System: Projector On -> Denon On"
  triggers:
    - trigger: state
      entity_id: remote.living_room_projector
      to: "on"
  conditions: []
  actions:
    - action: media_player.turn_on
      target:
        entity_id: media_player.denon_avr_x1500h
  mode: single

- alias: "Living Room: Media System: Denon Off -> Projector Off"
  triggers:
    - trigger: state
      entity_id: media_player.denon_avr_x1500h
      to: "off"
  conditions: []
  actions:
    - action: script.living_room_media_system_power_off
  mode: single
