---
- alias: "Home: Alarm: Disarmed"
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.ring_control_panel
      to: "disarmed"
  conditions:
    - condition: template
      value_template: "{{ trigger.from_state.state in ['armed_home', 'armed_away'] }}"
  variables:
    default_tilt: 88
  actions:
    - parallel:
        - action: script.cover_position_then_tilt
          data:
            cover_entity: cover.garden_door
            tilt_position: "{{ default_tilt }}"
        - action: script.cover_position_then_tilt
          data:
            cover_entity: cover.living_room_kitchen
            tilt_position: "{{ default_tilt }}"
        - action: script.cover_position_then_tilt
          data:
            cover_entity: cover.living_room_tv
            tilt_position: "{{ default_tilt }}"
        - action: script.cover_position_then_tilt
          data:
            cover_entity: cover.office
            tilt_position: "{{ default_tilt }}"
        - action: script.cover_position_then_tilt
          data:
            cover_entity: cover.tea_room
            tilt_position: 77
  mode: single
