---
- alias: "Lights: Storage Room"
  use_blueprint:
    path: lights/motion_lux.yaml
    input:
      motion_sensor: binary_sensor.fms3_home_security_motion_detection
      luminance_sensor: sensor.fms3_illuminance
      light_switch: switch.fs3_1
      wait_time: 300
