---
- alias: kitchen switch to light
  trigger:
    platform: state
    entity_id: switch.fs9_1
  action:
    service_template: "switch.turn_{{ trigger.to_state.state }}"
    entity_id: switch.fs12_1
