---
name: Pull Request

on:
  pull_request:

jobs:
  homeassistant:
    runs-on: ubuntu-latest
    name: Verify Home Assistant Configuration
    strategy:
      max-parallel: 4
      matrix:
        home-assistant-version:
          - stable
          - beta
          - dev

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare data
        run: |
          ./lifecycle/prepare.sh configuration

      - name: Check Home Assistant Configuration
        uses: frenck/action-home-assistant@v1
        with:
          path: configuration
          secrets: .ci/secrets.yaml
          version: "${{ matrix.home-assistant-version }}"
        env:
          POSTGRESQL_URI: postgresql://user:password@host:5432/db
