---
name: Pull Request

on:
  pull_request:

jobs:
  homeassistant:
    runs-on: ubuntu-latest
    name: Verify Home Assistant Configuration
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Prepare data
        run: |
          mkdir tmp
          cp -rf configuration/* tmp/
          cp .ci/secrets.yaml tmp/secrets.yaml
          # TODO: work-around for 'hass --script check_config'
          sed -i -e 's/^mobile_app:$/#mobile_app:/g' tmp/configuration.yaml
          ./lifecycle/prepare.sh tmp

      - run: |
          hass -c tmp/ --script check_config --info all
