---
name: Verify

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  homeassistant:
    runs-on: ubuntu-latest
    name: Verify Home Assistant Configuration
    strategy:
      max-parallel: 6
      matrix:
        home-assistant-version:
          - stable
          - beta
          - dev
        site:
          - vie

    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools

      - name: Prepare data
        run: |
          mkdir tmp
          cp -rf common/configuration/* tmp/
          cp -rf sites/${{ matrix.site }}/configuration/* tmp/
          ./lifecycle/prepare.sh tmp

      - name: Check Home Assistant Configuration
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4.1
        with:
          path: ./tmp
          secrets: .ci/secrets.yaml
          env_file: .ci/env
          version: "${{ matrix.home-assistant-version }}"
